### ISSUE TITLE
Tracking of supported and planned commands

### ISSUE THREAD

**Issue by andreondra** [sermatec-opensource/sermatec-inverter#45]
## Query
- [x] `0x98`: System Information
- [x] `0x0A`: Battery status
- [x] `0x0B`: Grid and PV status
- [x] `0x0C`: Running status
- [x] `0x95`: Working parameters
- [x] `0x0D`: Load and BMS status

## Setting
- [ ] `0x64`: Set inverter state (on/off)
- [ ] `0x66`: Set operating modes
